/*
Remote Config Admin API

# Overview Unity Remote Config is a cloud service that allows you to tune your game design without deploying new versions of your application. With Remote Config, you can:  Adapt your game to different types of players. Tune your game difficulty curve in near real time. Alter graphic quality based on device to optimize performance. Roll out new features gradually while monitoring impact. Tailor game settings to different regions or other player segments. Run campaign tests comparing colors, styles, prices, etc. Turn seasonal, holiday, or other time-sensitive events on or off. Enable or disable features for specific player segments or across the entire user base.  Define Game Overrides that control which players receive what settings updates, and when. Unity manages the delivery and assignment of those settings with minimal impact to performance. No update to your application is necessary. When a player launches your game, Remote Config detects contextual attributes used as game override conditions, based on Unity, the application, the user, or custom criteria that you define. The service then returns customized settings for each player according to the game overrides that apply to them. This allows different players using the same version of your game to have slightly different experiences. It also allows you to understand the impact each experience has on your business.  # Limitation * A configuration can have a max payload size of 5MB * A string limit is only of 65 535 characters 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityremoteconfig

import (
	"encoding/json"
)

// checks if the CampaignVariants type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignVariants{}

// CampaignVariants struct for CampaignVariants
type CampaignVariants struct {
	Name *string `json:"name,omitempty"`
	// Conditionally optional. If no variants have a weight then Remote Config will treat each variant as equally distributed. However, if one variant has a weight then all variants must define a weight.  If defined, the sum of all variant's weights must equal 100 
	Weight *int32 `json:"weight,omitempty"`
	Content []CampaignContentVariant `json:"content,omitempty"`
}

// NewCampaignVariants instantiates a new CampaignVariants object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignVariants() *CampaignVariants {
	this := CampaignVariants{}
	return &this
}

// NewCampaignVariantsWithDefaults instantiates a new CampaignVariants object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignVariantsWithDefaults() *CampaignVariants {
	this := CampaignVariants{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CampaignVariants) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignVariants) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CampaignVariants) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CampaignVariants) SetName(v string) {
	o.Name = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *CampaignVariants) GetWeight() int32 {
	if o == nil || IsNil(o.Weight) {
		var ret int32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignVariants) GetWeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Weight) {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *CampaignVariants) HasWeight() bool {
	if o != nil && !IsNil(o.Weight) {
		return true
	}

	return false
}

// SetWeight gets a reference to the given int32 and assigns it to the Weight field.
func (o *CampaignVariants) SetWeight(v int32) {
	o.Weight = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *CampaignVariants) GetContent() []CampaignContentVariant {
	if o == nil || IsNil(o.Content) {
		var ret []CampaignContentVariant
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignVariants) GetContentOk() ([]CampaignContentVariant, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *CampaignVariants) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []CampaignContentVariant and assigns it to the Content field.
func (o *CampaignVariants) SetContent(v []CampaignContentVariant) {
	o.Content = v
}

func (o CampaignVariants) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignVariants) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Weight) {
		toSerialize["weight"] = o.Weight
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

type NullableCampaignVariants struct {
	value *CampaignVariants
	isSet bool
}

func (v NullableCampaignVariants) Get() *CampaignVariants {
	return v.value
}

func (v *NullableCampaignVariants) Set(val *CampaignVariants) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignVariants) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignVariants) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignVariants(val *CampaignVariants) *NullableCampaignVariants {
	return &NullableCampaignVariants{value: val, isSet: true}
}

func (v NullableCampaignVariants) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignVariants) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


