/*
Remote Config Admin API

# Overview Unity Remote Config is a cloud service that allows you to tune your game design without deploying new versions of your application. With Remote Config, you can:  Adapt your game to different types of players. Tune your game difficulty curve in near real time. Alter graphic quality based on device to optimize performance. Roll out new features gradually while monitoring impact. Tailor game settings to different regions or other player segments. Run campaign tests comparing colors, styles, prices, etc. Turn seasonal, holiday, or other time-sensitive events on or off. Enable or disable features for specific player segments or across the entire user base.  Define Game Overrides that control which players receive what settings updates, and when. Unity manages the delivery and assignment of those settings with minimal impact to performance. No update to your application is necessary. When a player launches your game, Remote Config detects contextual attributes used as game override conditions, based on Unity, the application, the user, or custom criteria that you define. The service then returns customized settings for each player according to the game overrides that apply to them. This allows different players using the same version of your game to have slightly different experiences. It also allows you to understand the impact each experience has on your business.  # Limitation * A configuration can have a max payload size of 5MB * A string limit is only of 65 535 characters 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityremoteconfig

import (
	"encoding/json"
)

// checks if the UpdateConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateConfig{}

// UpdateConfig Request to update a Config
type UpdateConfig struct {
	// We currently only support one config type.
	Type string `json:"type"`
	// Array of `Setting` objects that represent the default values in your game.
	Value []Setting `json:"value"`
}

// NewUpdateConfig instantiates a new UpdateConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateConfig(type_ string, value []Setting) *UpdateConfig {
	this := UpdateConfig{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewUpdateConfigWithDefaults instantiates a new UpdateConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateConfigWithDefaults() *UpdateConfig {
	this := UpdateConfig{}
	return &this
}

// GetType returns the Type field value
func (o *UpdateConfig) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateConfig) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateConfig) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *UpdateConfig) GetValue() []Setting {
	if o == nil {
		var ret []Setting
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *UpdateConfig) GetValueOk() ([]Setting, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *UpdateConfig) SetValue(v []Setting) {
	o.Value = v
}

func (o UpdateConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableUpdateConfig struct {
	value *UpdateConfig
	isSet bool
}

func (v NullableUpdateConfig) Get() *UpdateConfig {
	return v.value
}

func (v *NullableUpdateConfig) Set(val *UpdateConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateConfig(val *UpdateConfig) *NullableUpdateConfig {
	return &NullableUpdateConfig{value: val, isSet: true}
}

func (v NullableUpdateConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


