/*
Remote Config Admin API

# Overview Unity Remote Config is a cloud service that allows you to tune your game design without deploying new versions of your application. With Remote Config, you can:  Adapt your game to different types of players. Tune your game difficulty curve in near real time. Alter graphic quality based on device to optimize performance. Roll out new features gradually while monitoring impact. Tailor game settings to different regions or other player segments. Run campaign tests comparing colors, styles, prices, etc. Turn seasonal, holiday, or other time-sensitive events on or off. Enable or disable features for specific player segments or across the entire user base.  Define Game Overrides that control which players receive what settings updates, and when. Unity manages the delivery and assignment of those settings with minimal impact to performance. No update to your application is necessary. When a player launches your game, Remote Config detects contextual attributes used as game override conditions, based on Unity, the application, the user, or custom criteria that you define. The service then returns customized settings for each player according to the game overrides that apply to them. This allows different players using the same version of your game to have slightly different experiences. It also allows you to understand the impact each experience has on your business.  # Limitation * A configuration can have a max payload size of 5MB * A string limit is only of 65 535 characters 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityremoteconfig

import (
	"encoding/json"
)

// checks if the ConfigCopyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigCopyRequest{}

// ConfigCopyRequest Request to copy Config Settings
type ConfigCopyRequest struct {
	SourceConfigId string `json:"sourceConfigId"`
	DestinationConfigId string `json:"destinationConfigId"`
	// Array of `Setting` keys that represent the Settings to be copied.
	Settings []string `json:"settings"`
}

// NewConfigCopyRequest instantiates a new ConfigCopyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigCopyRequest(sourceConfigId string, destinationConfigId string, settings []string) *ConfigCopyRequest {
	this := ConfigCopyRequest{}
	this.SourceConfigId = sourceConfigId
	this.DestinationConfigId = destinationConfigId
	this.Settings = settings
	return &this
}

// NewConfigCopyRequestWithDefaults instantiates a new ConfigCopyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigCopyRequestWithDefaults() *ConfigCopyRequest {
	this := ConfigCopyRequest{}
	return &this
}

// GetSourceConfigId returns the SourceConfigId field value
func (o *ConfigCopyRequest) GetSourceConfigId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceConfigId
}

// GetSourceConfigIdOk returns a tuple with the SourceConfigId field value
// and a boolean to check if the value has been set.
func (o *ConfigCopyRequest) GetSourceConfigIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceConfigId, true
}

// SetSourceConfigId sets field value
func (o *ConfigCopyRequest) SetSourceConfigId(v string) {
	o.SourceConfigId = v
}

// GetDestinationConfigId returns the DestinationConfigId field value
func (o *ConfigCopyRequest) GetDestinationConfigId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationConfigId
}

// GetDestinationConfigIdOk returns a tuple with the DestinationConfigId field value
// and a boolean to check if the value has been set.
func (o *ConfigCopyRequest) GetDestinationConfigIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationConfigId, true
}

// SetDestinationConfigId sets field value
func (o *ConfigCopyRequest) SetDestinationConfigId(v string) {
	o.DestinationConfigId = v
}

// GetSettings returns the Settings field value
func (o *ConfigCopyRequest) GetSettings() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value
// and a boolean to check if the value has been set.
func (o *ConfigCopyRequest) GetSettingsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Settings, true
}

// SetSettings sets field value
func (o *ConfigCopyRequest) SetSettings(v []string) {
	o.Settings = v
}

func (o ConfigCopyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigCopyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sourceConfigId"] = o.SourceConfigId
	toSerialize["destinationConfigId"] = o.DestinationConfigId
	toSerialize["settings"] = o.Settings
	return toSerialize, nil
}

type NullableConfigCopyRequest struct {
	value *ConfigCopyRequest
	isSet bool
}

func (v NullableConfigCopyRequest) Get() *ConfigCopyRequest {
	return v.value
}

func (v *NullableConfigCopyRequest) Set(val *ConfigCopyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigCopyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigCopyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigCopyRequest(val *ConfigCopyRequest) *NullableConfigCopyRequest {
	return &NullableConfigCopyRequest{value: val, isSet: true}
}

func (v NullableConfigCopyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigCopyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


