/*
Remote Config Admin API

# Overview Unity Remote Config is a cloud service that allows you to tune your game design without deploying new versions of your application. With Remote Config, you can:  Adapt your game to different types of players. Tune your game difficulty curve in near real time. Alter graphic quality based on device to optimize performance. Roll out new features gradually while monitoring impact. Tailor game settings to different regions or other player segments. Run campaign tests comparing colors, styles, prices, etc. Turn seasonal, holiday, or other time-sensitive events on or off. Enable or disable features for specific player segments or across the entire user base.  Define Game Overrides that control which players receive what settings updates, and when. Unity manages the delivery and assignment of those settings with minimal impact to performance. No update to your application is necessary. When a player launches your game, Remote Config detects contextual attributes used as game override conditions, based on Unity, the application, the user, or custom criteria that you define. The service then returns customized settings for each player according to the game overrides that apply to them. This allows different players using the same version of your game to have slightly different experiences. It also allows you to understand the impact each experience has on your business.  # Limitation * A configuration can have a max payload size of 5MB * A string limit is only of 65 535 characters 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityremoteconfig

import (
	"encoding/json"
)

// checks if the GetEnvironmentsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEnvironmentsResponse{}

// GetEnvironmentsResponse struct for GetEnvironmentsResponse
type GetEnvironmentsResponse struct {
	Environments []Environment `json:"environments,omitempty"`
}

// NewGetEnvironmentsResponse instantiates a new GetEnvironmentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEnvironmentsResponse() *GetEnvironmentsResponse {
	this := GetEnvironmentsResponse{}
	return &this
}

// NewGetEnvironmentsResponseWithDefaults instantiates a new GetEnvironmentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEnvironmentsResponseWithDefaults() *GetEnvironmentsResponse {
	this := GetEnvironmentsResponse{}
	return &this
}

// GetEnvironments returns the Environments field value if set, zero value otherwise.
func (o *GetEnvironmentsResponse) GetEnvironments() []Environment {
	if o == nil || IsNil(o.Environments) {
		var ret []Environment
		return ret
	}
	return o.Environments
}

// GetEnvironmentsOk returns a tuple with the Environments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEnvironmentsResponse) GetEnvironmentsOk() ([]Environment, bool) {
	if o == nil || IsNil(o.Environments) {
		return nil, false
	}
	return o.Environments, true
}

// HasEnvironments returns a boolean if a field has been set.
func (o *GetEnvironmentsResponse) HasEnvironments() bool {
	if o != nil && !IsNil(o.Environments) {
		return true
	}

	return false
}

// SetEnvironments gets a reference to the given []Environment and assigns it to the Environments field.
func (o *GetEnvironmentsResponse) SetEnvironments(v []Environment) {
	o.Environments = v
}

func (o GetEnvironmentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEnvironmentsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Environments) {
		toSerialize["environments"] = o.Environments
	}
	return toSerialize, nil
}

type NullableGetEnvironmentsResponse struct {
	value *GetEnvironmentsResponse
	isSet bool
}

func (v NullableGetEnvironmentsResponse) Get() *GetEnvironmentsResponse {
	return v.value
}

func (v *NullableGetEnvironmentsResponse) Set(val *GetEnvironmentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEnvironmentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEnvironmentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEnvironmentsResponse(val *GetEnvironmentsResponse) *NullableGetEnvironmentsResponse {
	return &NullableGetEnvironmentsResponse{value: val, isSet: true}
}

func (v NullableGetEnvironmentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEnvironmentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


