/*
Remote Config Admin API

# Overview Unity Remote Config is a cloud service that allows you to tune your game design without deploying new versions of your application. With Remote Config, you can:  Adapt your game to different types of players. Tune your game difficulty curve in near real time. Alter graphic quality based on device to optimize performance. Roll out new features gradually while monitoring impact. Tailor game settings to different regions or other player segments. Run campaign tests comparing colors, styles, prices, etc. Turn seasonal, holiday, or other time-sensitive events on or off. Enable or disable features for specific player segments or across the entire user base.  Define Game Overrides that control which players receive what settings updates, and when. Unity manages the delivery and assignment of those settings with minimal impact to performance. No update to your application is necessary. When a player launches your game, Remote Config detects contextual attributes used as game override conditions, based on Unity, the application, the user, or custom criteria that you define. The service then returns customized settings for each player according to the game overrides that apply to them. This allows different players using the same version of your game to have slightly different experiences. It also allows you to understand the impact each experience has on your business.  # Limitation * A configuration can have a max payload size of 5MB * A string limit is only of 65 535 characters 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityremoteconfig

import (
	"encoding/json"
)

// checks if the RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response{}

// RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response struct for RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response
type RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response struct {
	Code *int32 `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// List of Setting keys that could not be copied due to a type conflict
	Settings []string `json:"settings,omitempty"`
}

// NewRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response instantiates a new RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response() *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response {
	this := RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response{}
	return &this
}

// NewRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409ResponseWithDefaults instantiates a new RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409ResponseWithDefaults() *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response {
	this := RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) SetCode(v int32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) SetMessage(v string) {
	o.Message = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) GetSettings() []string {
	if o == nil || IsNil(o.Settings) {
		var ret []string
		return ret
	}
	return o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) GetSettingsOk() ([]string, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given []string and assigns it to the Settings field.
func (o *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) SetSettings(v []string) {
	o.Settings = v
}

func (o RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	return toSerialize, nil
}

type NullableRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response struct {
	value *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response
	isSet bool
}

func (v NullableRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) Get() *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response {
	return v.value
}

func (v *NullableRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) Set(val *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response(val *RemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) *NullableRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response {
	return &NullableRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response{value: val, isSet: true}
}

func (v NullableRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoteConfigV1ProjectsProjectIdConfigsCopytoPost409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


