/*
Remote Config Admin API

# Overview Unity Remote Config is a cloud service that allows you to tune your game design without deploying new versions of your application. With Remote Config, you can:  Adapt your game to different types of players. Tune your game difficulty curve in near real time. Alter graphic quality based on device to optimize performance. Roll out new features gradually while monitoring impact. Tailor game settings to different regions or other player segments. Run campaign tests comparing colors, styles, prices, etc. Turn seasonal, holiday, or other time-sensitive events on or off. Enable or disable features for specific player segments or across the entire user base.  Define Game Overrides that control which players receive what settings updates, and when. Unity manages the delivery and assignment of those settings with minimal impact to performance. No update to your application is necessary. When a player launches your game, Remote Config detects contextual attributes used as game override conditions, based on Unity, the application, the user, or custom criteria that you define. The service then returns customized settings for each player according to the game overrides that apply to them. This allows different players using the same version of your game to have slightly different experiences. It also allows you to understand the impact each experience has on your business.  # Limitation * A configuration can have a max payload size of 5MB * A string limit is only of 65 535 characters 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityremoteconfig

import (
	"encoding/json"
)

// checks if the DefaultEnvironmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultEnvironmentResponse{}

// DefaultEnvironmentResponse A environment
type DefaultEnvironmentResponse struct {
	Id string `json:"id"`
}

// NewDefaultEnvironmentResponse instantiates a new DefaultEnvironmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultEnvironmentResponse(id string) *DefaultEnvironmentResponse {
	this := DefaultEnvironmentResponse{}
	this.Id = id
	return &this
}

// NewDefaultEnvironmentResponseWithDefaults instantiates a new DefaultEnvironmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultEnvironmentResponseWithDefaults() *DefaultEnvironmentResponse {
	this := DefaultEnvironmentResponse{}
	return &this
}

// GetId returns the Id field value
func (o *DefaultEnvironmentResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DefaultEnvironmentResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DefaultEnvironmentResponse) SetId(v string) {
	o.Id = v
}

func (o DefaultEnvironmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultEnvironmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableDefaultEnvironmentResponse struct {
	value *DefaultEnvironmentResponse
	isSet bool
}

func (v NullableDefaultEnvironmentResponse) Get() *DefaultEnvironmentResponse {
	return v.value
}

func (v *NullableDefaultEnvironmentResponse) Set(val *DefaultEnvironmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultEnvironmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultEnvironmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultEnvironmentResponse(val *DefaultEnvironmentResponse) *NullableDefaultEnvironmentResponse {
	return &NullableDefaultEnvironmentResponse{value: val, isSet: true}
}

func (v NullableDefaultEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultEnvironmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


