/*
Remote Config Admin API

# Overview Unity Remote Config is a cloud service that allows you to tune your game design without deploying new versions of your application. With Remote Config, you can:  Adapt your game to different types of players. Tune your game difficulty curve in near real time. Alter graphic quality based on device to optimize performance. Roll out new features gradually while monitoring impact. Tailor game settings to different regions or other player segments. Run campaign tests comparing colors, styles, prices, etc. Turn seasonal, holiday, or other time-sensitive events on or off. Enable or disable features for specific player segments or across the entire user base.  Define Game Overrides that control which players receive what settings updates, and when. Unity manages the delivery and assignment of those settings with minimal impact to performance. No update to your application is necessary. When a player launches your game, Remote Config detects contextual attributes used as game override conditions, based on Unity, the application, the user, or custom criteria that you define. The service then returns customized settings for each player according to the game overrides that apply to them. This allows different players using the same version of your game to have slightly different experiences. It also allows you to understand the impact each experience has on your business.  # Limitation * A configuration can have a max payload size of 5MB * A string limit is only of 65 535 characters 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityremoteconfig

import (
	"encoding/json"
)

// checks if the RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response{}

// RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response struct for RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response
type RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response struct {
	Configs []Config `json:"configs,omitempty"`
}

// NewRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response instantiates a new RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response() *RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response {
	this := RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response{}
	return &this
}

// NewRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200ResponseWithDefaults instantiates a new RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200ResponseWithDefaults() *RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response {
	this := RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response{}
	return &this
}

// GetConfigs returns the Configs field value if set, zero value otherwise.
func (o *RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) GetConfigs() []Config {
	if o == nil || IsNil(o.Configs) {
		var ret []Config
		return ret
	}
	return o.Configs
}

// GetConfigsOk returns a tuple with the Configs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) GetConfigsOk() ([]Config, bool) {
	if o == nil || IsNil(o.Configs) {
		return nil, false
	}
	return o.Configs, true
}

// HasConfigs returns a boolean if a field has been set.
func (o *RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) HasConfigs() bool {
	if o != nil && !IsNil(o.Configs) {
		return true
	}

	return false
}

// SetConfigs gets a reference to the given []Config and assigns it to the Configs field.
func (o *RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) SetConfigs(v []Config) {
	o.Configs = v
}

func (o RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Configs) {
		toSerialize["configs"] = o.Configs
	}
	return toSerialize, nil
}

type NullableRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response struct {
	value *RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response
	isSet bool
}

func (v NullableRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) Get() *RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response {
	return v.value
}

func (v *NullableRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) Set(val *RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response(val *RemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) *NullableRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response {
	return &NullableRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response{value: val, isSet: true}
}

func (v NullableRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoteConfigV1ProjectsProjectIdEnvironmentsEnvironmentIdConfigsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


