/*
Remote Config Admin API

# Overview Unity Remote Config is a cloud service that allows you to tune your game design without deploying new versions of your application. With Remote Config, you can:  Adapt your game to different types of players. Tune your game difficulty curve in near real time. Alter graphic quality based on device to optimize performance. Roll out new features gradually while monitoring impact. Tailor game settings to different regions or other player segments. Run campaign tests comparing colors, styles, prices, etc. Turn seasonal, holiday, or other time-sensitive events on or off. Enable or disable features for specific player segments or across the entire user base.  Define Game Overrides that control which players receive what settings updates, and when. Unity manages the delivery and assignment of those settings with minimal impact to performance. No update to your application is necessary. When a player launches your game, Remote Config detects contextual attributes used as game override conditions, based on Unity, the application, the user, or custom criteria that you define. The service then returns customized settings for each player according to the game overrides that apply to them. This allows different players using the same version of your game to have slightly different experiences. It also allows you to understand the impact each experience has on your business.  # Limitation * A configuration can have a max payload size of 5MB * A string limit is only of 65 535 characters 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package unityremoteconfig

import (
	"encoding/json"
)

// checks if the CampaignContentVariant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignContentVariant{}

// CampaignContentVariant struct for CampaignContentVariant
type CampaignContentVariant struct {
	Type string `json:"type"`
	Values []Setting `json:"values"`
}

// NewCampaignContentVariant instantiates a new CampaignContentVariant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignContentVariant(type_ string, values []Setting) *CampaignContentVariant {
	this := CampaignContentVariant{}
	this.Type = type_
	this.Values = values
	return &this
}

// NewCampaignContentVariantWithDefaults instantiates a new CampaignContentVariant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignContentVariantWithDefaults() *CampaignContentVariant {
	this := CampaignContentVariant{}
	return &this
}

// GetType returns the Type field value
func (o *CampaignContentVariant) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CampaignContentVariant) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CampaignContentVariant) SetType(v string) {
	o.Type = v
}

// GetValues returns the Values field value
func (o *CampaignContentVariant) GetValues() []Setting {
	if o == nil {
		var ret []Setting
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *CampaignContentVariant) GetValuesOk() ([]Setting, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *CampaignContentVariant) SetValues(v []Setting) {
	o.Values = v
}

func (o CampaignContentVariant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignContentVariant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["values"] = o.Values
	return toSerialize, nil
}

type NullableCampaignContentVariant struct {
	value *CampaignContentVariant
	isSet bool
}

func (v NullableCampaignContentVariant) Get() *CampaignContentVariant {
	return v.value
}

func (v *NullableCampaignContentVariant) Set(val *CampaignContentVariant) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignContentVariant) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignContentVariant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignContentVariant(val *CampaignContentVariant) *NullableCampaignContentVariant {
	return &NullableCampaignContentVariant{value: val, isSet: true}
}

func (v NullableCampaignContentVariant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignContentVariant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


