openapi: 3.0.0
info:
  description: |
    # Overview
    Unity Remote Config is a cloud service that allows you to tune your game design without deploying new versions of your application. With Remote Config, you can:

    Adapt your game to different types of players.
    Tune your game difficulty curve in near real time.
    Alter graphic quality based on device to optimize performance.
    Roll out new features gradually while monitoring impact.
    Tailor game settings to different regions or other player segments.
    Run campaign tests comparing colors, styles, prices, etc.
    Turn seasonal, holiday, or other time-sensitive events on or off.
    Enable or disable features for specific player segments or across the entire user base.

    Define Game Overrides that control which players receive what settings updates, and when. Unity manages the delivery and assignment of those settings with minimal impact to performance. No update to your application is necessary. When a player launches your game, Remote Config detects contextual attributes used as game override conditions, based on Unity, the application, the user, or custom criteria that you define. The service then returns customized settings for each player according to t[...]

    # Limitation
    * A configuration can have a max payload size of 5MB
    * A string limit is only of 65 535 characters
  title: Remote Config Admin API
  version: v1
servers:
- url: https://services.api.unity.com
tags:
- description: Manage multiple environments to allow for use cases around separate
    development and release environments as well as version control. Each project
    has a default environment which can not be deleted. The default environment is
    served when no other environment is specified.
  name: Environments
- description: "Interact with configs to store settings. A Setting is a key that you’\
    ll map to a parameter in your game code, so you can dynamically change its value\
    \ without changing your code."
  name: Configs
- description: "Game Overrides allow you to optimize your player experience by making\
    \ it easy to override default config variables within your game without requiring\
    \ a code update or app deployment. You can target specific groups of players for\
    \ seasonal or promotional Overrides, or you can experiment with A/B testing to\
    \ increase engagement for specific player segments. Game Overrides are built on-top\
    \ of Remote Config, with integrations with several other Unity products."
  name: Game Overrides
paths:
  /remote-config/v1/projects/{projectId}/environments:
    get:
      description: Returns the list of environments for a Project.
      security:
      - ServiceAccount:
        - remote_config.configs.list
      summary: Get All Environments
      tags:
      - Environments
  /remote-config/v1/projects/{projectId}/environments/{environmentId}:
    get:
      description: Return environment for a given ID
      security:
      - ServiceAccount:
        - remote_config.configs.list
      summary: Get Environment
      tags:
      - Environments
  /remote-config/v1/projects/{projectId}/environments/default:
    get:
      description: Obtain the id of the default environment.
      security:
      - ServiceAccount:
        - remote_config.configs.list
      summary: Get Default Environment
      tags:
      - Environments
  /remote-config/v1/projects/{projectId}/configs:
    get:
      description: Obtain the configs with the default environment 'production' or
        specified environment id
      security:
      - ServiceAccount:
        - remote_config.configs.list
      summary: Get config with the default environment
      tags:
      - Configs
    post:
      description: Create Config.
      security:
      - ServiceAccount:
        - remote_config.configs.create
      summary: Create Config
      tags:
      - Configs
  /remote-config/v1/projects/{projectId}/configs/{configId}:
    delete:
      description: Deletes an existing Config
      security:
      - ServiceAccount:
        - remote_config.configs.delete
      summary: Delete Config
      tags:
      - Configs
    get:
      description: Returns Config for a given ID
      security:
      - ServiceAccount:
        - remote_config.configs.list
      summary: Get Config
      tags:
      - Configs
    put:
      description: Updates the value of an existing Config
      security:
      - ServiceAccount:
        - remote_config.configs.update
      summary: Update Config
      tags:
      - Configs
  /remote-config/v1/projects/{projectId}/environments/{environmentId}/configs:
    get:
      description: "Returns the list of all configs for a Environment. Currently,\
        \ the only supported config type is \"settings\""
      security:
      - ServiceAccount:
        - remote_config.configs.get
      summary: Get Configs by Environment ID
      tags:
      - Configs
  /remote-config/v1/projects/{projectId}/configs:copyto:
    post:
      description: Copies specified settings from a source Config to a destination
        Config
      security:
      - ServiceAccount:
        - remote_config.configs.create
      summary: Copy Config Settings
      tags:
      - Configs
  /remote-config/v1/projects/{projectId}/campaigns/{campaignId}:
    delete:
      description: Deletes existing game override
      operationId: deleteGameOverride
      security:
      - ServiceAccount:
        - remote_config.game_overrides.delete
      summary: Delete a single game override
      tags:
      - Game Overrides
    get:
      description: Retrieve a game override
      operationId: getGameOverride
      security:
      - ServiceAccount:
        - remote_config.game_overrides.list
      summary: Get a single game override
      tags:
      - Game Overrides
    put:
      description: Updates an existing game override
      operationId: updateGameOverride
      security:
      - ServiceAccount:
        - remote_config.game_overrides.update
      summary: Update a single game override
      tags:
      - Game Overrides
components:
  securitySchemes:
    ServiceAccount:
      description: |-
        To get started with Authentication, please visit the [Service Account Authentication section](https://services.docs.unity.com/docs/service-account-auth).

        For this API, you will need to add the following role(s) to your service account:
          | Role Type | Role Name | Permissions |
          | --- | --- | --- |
          | Project Level Role | Remote Config API Reader |<ul><li>remote_config.configs.get</li><li>remote_config.configs.list</li><li>remote_config.game_overrides.list</li><li>remote_config.game_overrides.get</li></ul>|
          | Project Level Role | Remote Config API Editor |<ul><li>remote_config.configs.create</li><li>remote_config.configs.delete</li><li>remote_config.configs.update</li><li>remote_config.game_overrides.create</li><li>remote_config.game_overrides.update</li><li>remote_config.game_overrides.delete</li></ul>|
          | Project Level Role | Remote Config Admin |<ul><li>remote_config.configs.create</li><li>remote_config.configs.get</li><li>remote_config.configs.list</li><li>remote_config.configs.delete</li><li>remote_config.configs.update</li><li>remote_config.game_overrides.create</li><li>remote_config.game_overrides.update</li><li>remote_config.game_overrides.delete</li><li>remote_config.game_overrides.list</li><li>remote_config.game_overrides.get</li></ul> |
      scheme: basic
      type: http
